---
title: "K EDA"
author: "Kynan Desouza-Chen"
date: "2022-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(readr)
library(rpart)
library(rpart.plot)
```

```{r, cache=TRUE}
majordata <- read_csv("C:\\Users\\kdeso\\OneDrive\\Documents\\GitHub\\majordata.csv")
View(majordata)
```

```{r}
ggplot(majordata, aes(x=tot_enroll_ct))+
  geom_density()+
  facet_wrap(~terms_enrl_ct)
```

```{r}
majordata %>%
  mutate(maj_MathSci = ifelse(major1_division == "Natural Sciences and Mathematics" | major2_division == "Natural Sciences and Mathematics" | major3_division == "Natural Sciences and Mathematics", TRUE, FALSE)) %>% 
  mutate(maj_MathSci = replace_na(maj_MathSci, FALSE)) %>%
  count(maj_MathSci, studied_away) %>%
  group_by(maj_MathSci) %>%
  mutate(perc = n/sum(n)) %>%
  filter(studied_away == 1) %>%
  group_by(studied_away) %>%
  mutate(ratio = perc/(sum(perc) - perc)) #%>%
#  filter(ratio == max(ratio)) %>%
#  group_by(ratio) %>%
#  select(ratio)
```

> Walk through the criteria for determining a STEM major. Explain prefix count. Draw conclusions - non-STEM majors have more variety in the courses they take

```{r}
majordata %>%
  mutate(maj_MathSci = if_else(major1_division == "Natural Sciences and Mathematics" | major2_division == "Natural Sciences and Mathematics" | major3_division == "Natural Sciences and Mathematics", TRUE, FALSE)) %>% 
  mutate(maj_MathSci = replace_na(maj_MathSci, FALSE)) %>%
  ggplot(aes(x = prefix_count, fill = maj_MathSci))+
  geom_density(alpha = 0.2)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  scale_fill_manual(values = c("blue", "green"))+
  labs(title = "Course Variety in STEM and non-STEM majors", x = "Number of Unique Departments with a Class Taken", y = "Density", fill = "STEM major")
```

```{r}
first_gen_only <- majordata %>% 
  drop_na(first_gen) %>%
  filter(first_gen == "first gen") %>%
  select(-c(StudentID))

View(first_gen_only)
```


```{r}
first_gen_major <- majordata %>% 
  drop_na(first_gen) %>%
  select(!starts_with('maj_')) %>%
  select(-c("StudentID", "grad_year"))
  
shuffle_index <- sample(1:nrow(first_gen_major))

first_gen_major <- first_gen_major[shuffle_index, ]

clean_first_gen <- first_gen_major %>%
  select(c(first_gen, major1, major2))

create_train_test <- function(data, size = 0.8, train = TRUE) {
    n_row = nrow(data)
    total_row = size * n_row
    train_sample <- 1:total_row
    if (train == TRUE) {
        return (data[train_sample, ])
    } else {
        return (data[-train_sample, ])
    }
}

data_train <- create_train_test(clean_first_gen, 0.8, train = TRUE)

data_test <- create_train_test(clean_first_gen, 0.8, train = FALSE)

fit <- rpart(first_gen~., data = data_train, method = "class")

predict_unseen <- predict(fit, data_test, type = "class")
    
table_mat <- table(data_test$first_gen, predict_unseen)

accuracy_Test <- sum(diag(table_mat)) / sum(table_mat)
accuracy_Test
    
rpart.plot(fit, extra = 106)
```






